os2tk45: fix compiler errors by GCC 14
Since GCC14, some warnings are treated as errors.
See https://gcc.gnu.org/gcc-14/porting_to.html#warnings-as-errors.
As a result, there are cases which compilation fails. For example,

-----
f:/lang/os2tk45/h/os2medef.h:35:15: error: type defaults to 'int' in declaration of 'LPTR' [-Wimplicit-int]
   35 | typedef FAR * LPTR;
      |               ^~~~
f:/lang/os2tk45/h/os2medef.h:36:15: error: type defaults to 'int' in declaration of 'LPRECT' [-Wimplicit-int]
   36 | typedef FAR * LPRECT;
      |               ^~~~~~
-----

See https://github.com/bitwiseworks/os2tk45/issues/7.

    new file:   os2tk45/0002-correct-implicit-int-pointer-type-in-os2medef_h.patch